### ISSUE TITLE
scss-lint has become scss_lint

### ISSUE THREAD

**Issue by elidupuis** [pre-commit/mirrors-scss-lint#1]
Looks like the `scss-lint` gem has been renamed to `scss_lint` :astonished: 

- Old gem: https://rubygems.org/gems/scss-lint/
- New gem: https://rubygems.org/gems/scss_lint

From their [changelog](https://github.com/brigade/scss-lint/blob/master/CHANGELOG.md#0380):
> Rename scss-lint gem to scss_lint to follow RubyGems best practices for naming gems. This only affects the name you use in Gemfiles or when you gem install; everything else remains the same.

This mirror uses the old gem which tops out at version 0.38. The new gem picks up at 0.38 and has recent releases up to 0.43.2. 

I've created a [mirror for the new gem](https://github.com/elidupuis/mirrors-scss_lint) for now but I'm wondering what your thoughts are around this issue. Would it work to simply update the [`hooks.yaml` file ](https://github.com/pre-commit/mirrors-scss-lint/blob/master/hooks.yaml#L2) to use `scss_lint` for the gem name? Could end users still grab an old SHA (pre 0.38) without breaking stuff?

**Comment by asottile** [comment]
Yeah, I'll just update this repo (making yours obsolete, eheh).  Thanks for the heads up.  The old gem still works (we're using it at yelp).

**Comment by elidupuis** [comment]
Haha. You're too quick! I just submitted #2 PR before I saw your response!

**Comment by asottile** [comment]
This is how I regenned:

`pre-commit-mirror mirrors-scss-lint/ ruby scss_lint '\.scss$' --entry scss-lint`

(The first commit required manual surgery in pre-commit-mirror-maker)

**Comment by elidupuis** [comment]
Makes sense! Didn't think of overriding `--entry scss-lint`. :+1:
